### PR TITLE
Updated failing test for union of steps

### PR DESCRIPTION
**Pull request by rubanm**
See https://github.com/cwensel/cascading/pull/52 for context

### CODE REVIEW

**Comment by cwensel** [comment]
OK, just now getting to this. looks like test passes for both Tez and Local, but not MR. let me try and hammer something out.

**Comment by cwensel** [comment]
Have a fix, missing match for the Checkpoint in the TapBalanceGroupSplitTransformer rule.

Running local tests now and should have a wip up tomorrow. I can also drop binaries into a dropbox folder if you want to test locally before it publishes.

**Comment by rubanm** [comment]
@cwensel Thanks! I can wait for the wip to be published.

**Comment by cwensel** [comment]
fwiw, here is the patch for the relevant bits: https://gist.github.com/cwensel/717027caf0056ac35fb24db5683f630b

pretty trivial change, you might find it interesting to run your test with the tracing enabled (on a mac)

`-Dtest.cluster.enabled=false -Dtest.traceplan.enabled=true`

the plan directory under the build for the relevant sub-project will have lots of dot files showing the planner at work. this handily converts them to pdf `dot *.dot -Tpdf -O -Nshape=box` (which is a convenient finder action via automator)

diagnosing planner errors and adding/updating rules will be very helpful as you encounter other edge cases.

**Comment by cwensel** [comment]
wip-61 published.

http://conjars.org/cascading/cascading-core

let me know if the issue persists.

**Comment by rubanm** [comment]
@cwensel verified the fix. Thanks

**Pull request closed without merging**
