### PR TITLE
Preliminary Hadoop 3 support

### PR DESCRIPTION
**Pull request by jonshea**
This commit introduces preliminary Hadoop 3 support in the form of `cascading-hadoop3-X` modules built against Hadoop 3.

* Renamed `cascading-local-hadoop2-io` to `cascading-local-hadoop3-io`

* Renamed `cascading-hadoop2-common` to `cascading-hadoop3-common`

* Renamed `cascading-hadoop2-io` to `cascading-hadoop3-io`

* Copied `cascading-hadoop2-mr1` to `cascading-hadoop3-mr1`

* Copied `cascading-hadoop2-tez` to `cascading-hadoop3-tez`

* Copied `cascading-hadoop2-tez-stats` to `cascading-hadoop3-tez-stats`

* In the `cascading-hadoop3-*` packages, updated the version number of
  the hadoop external dependency to 3.2.1 (current version of the latest
  AWS EMR ReleaseLabel, 6.2.x).

* Did a quick find-and-replace update of hadoop 2-like references in the
  `cascading-hadoop3-*` packages to hadoop 3.

* Removed the deprecated `jcenter()` repository from

* Upgraded `net.wensel.riffle` from `1.10` to `1.2.0`.Exploratory Hadoop 3 Support WIP

### CODE REVIEW

**Comment by jonshea** [comment]
This is a preliminary PR to move cascading to Hadoop 3. The `cascading-hadoop2-X` modules have been renamed to `cascading-hadoop3-X`, as well as `cascading-local-hadoop2-io`, and the hadoop dependencies have been updated to 3.2.1. 

Unlike the branch we previously discussed, I have also provided the same treatment to `cascading-hadoop2-tez` and `cascading-hadoop2-tez-stats`. I don’t know much about tez, so I it is possible that more work is required here? But tests at least seem to pass. There are many classes in the tez modules with names like `Hadoop2TezX` that I have not yet renamed, but I am happy to do so. If we do not want to support both hadoop2 and hadoop3 simultaneously, then perhaps it makes it makes sense to renamed these files to `HadoopTezX` and drop the hadoop version number? Maybe it makes sense to do the same for the `cascading-hadoop-X` module / jar names too? I am happy to defer to your preference here.

Commit history for the moved / renamed files is preserved when queried with with the `--follow` flag, for example `git log --follow`, but not without. I am not aware of any way to preserve history without the `--follow` flag.

All tests pass when running both `./gradlew clean cascading-local:test cascading-local:platformTest` and `./gradlew test`.

If you can think of anything else that needs to be done then I am happy to look into it if you would point me in the right direction.

**Comment by cwensel** [comment]
excellent!

So I started a wip-4.5 branch here we can merge into: https://github.com/cwensel/cascading/tree/wip-4.5

Feel free to rebase against that branch and resubmit the PR. Sorry I didn't get to that sooner.

Also, if you can run `./gradlew clean check` that will run the platform tests for hadoop as well as everything else. You might find a server in a corner to run it on, you don't want to tie up your productivity computer.

I'd be surprised if there are no errors. 

If there are, we can put a public branch on this repo and work through them one at a time.

Also, since the tests run for 3 hours, we can figure out a way to share the results of the build server I'm running behind a firewall. Let me research options.

**Comment by hazel-sudz** [comment]
@cwensel I'm interested in continuing this work along with @jonshea and working through the test failures. I think your idea of merging into the wip-4.5 is great so that we can open PRs against that branch until it is ready. 

I will rebase this branch against wip-4.5 and open a new PR

**Comment by cwensel** [comment]
was resolved in this commit fea3a7b45752e093425a534216731e91aadc7831

**Pull request closed without merging**
