### PR TITLE
Adding flow step listener

### PR DESCRIPTION
**Pull request by Ahmed--Mohsen**
FlowStepListener interface for flow step updates
I need this interface to add support of cascading on ambrose https://github.com/twitter/ambrose/pull/61

### CODE REVIEW

**Comment by cwensel** [comment]
Hey thanks!

Before I can integrate this, I do need a contributor agreement signed. You can find a copy here

http://files.concurrentinc.com/agreements/Concurrent_Contributor_Agreement.doc

thanks!

**Comment by cwensel** [comment]
some quick comments. 

wondering if it makes sense to give each step its own collection of listeners, vs having Flow hold global ones for all its steps. but do add a helper on flow to add a listener to all its steps?

I also added a slight bit of cleanup as can be seen here

https://gist.github.com/cwensel/3c8d3092c8e461319a3b

**Comment by Ahmed--Mohsen** [comment]
Hey cwensel,
First of all thanks a lot for replying ... 
Here you are the signed agreement https://www.dropbox.com/s/u40ah3e5z2waim3/Concurrent_Contributor_Agreement.pdf

About each step vs. global ones: I choose the later cause the user will have no clue about the steps the flow has till run time, So, I gave the flow the responsibility to assign listeners for its steps

Also it makes more sense when integrating with Ambrose, i.e. It will be much easier for the users to just add a couple of code to track their execution progress instead of attaching the listener for every single step
tfidfFlow.addListener(server);
tfidfFlow.addStepListener(server);
tfidfFlow.complete();

**Comment by cwensel** [comment]
If you can send me your email, I can have that in our records.

I like having addStepListener on the Flow, but it should iteratively add to the steps. this way each step can also have its own listeners. it also keeps the Steps from having knowledge of inside the Flow.

**Comment by Ahmed--Mohsen** [comment]
My email: Ahmed7890@gmail.com

So, you want each step to have there own listeners and an addListener method and the flow would act as a mediator  to add listeners for all the owning steps ?

**Comment by cwensel** [comment]
yes, that would be the most utilitarian and least coupling implementation.

On Nov 14, 2013, at 1:40 PM, Ahmed Mohsen notifications@github.com wrote:

> My email: Ahmed7890@gmail.com
> 
> So, you want each step to have there own listeners and an addListener method and the flow would act as a mediator to add listeners for all the owning steps ?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by Ahmed--Mohsen** [comment]
Done!

**Comment by cwensel** [comment]
ok, just realized there are no supporting tests.

if you can apply the following patch to your base and add tests to that, that would be much appreciated. there should be a comparable test in the suite for the flow listeners.

i've fixed a few issues in that patch. 

https://gist.github.com/cwensel/8b1abda598404a91b6b3

**Comment by Ahmed--Mohsen** [comment]
I have applied the patch manually as it conflicts with my last commit ... I think the major issue is the using of the term running instead of progressing, Am I correct?

I have also added a test for the FlowStepListener similar to that found for the FlowListener

There exist an issue with me that whenever I call getTaskStats on HadoopStepStats I got an empty hash
HadoopStepStats stats = (HadoopStepStats)flowStep.getFlowStepStats();
stats.captureDetail();
stats.getTaskStats(); //return {}

also the number of mapper and reducers are always zero
stats.getNumMapTasks(); //return 0

one last thing is that the mapProgress and reduceProgress go from zero to 100% directly even if the step is still running and not completed yet

Is there something wrong I am doing or it may be because I run hadoop using Netbeans 

Thanks in advance and sorry for the long comment!

**Comment by cwensel** [comment]
those methods aren't wired up since there isn't a way to get the actual values. they should have been deprecated.

On Nov 18, 2013, at 1:58 PM, Ahmed Mohsen notifications@github.com wrote:

> I have applied the patch manually as it conflicts with my last commit ... I think the major issue is the using of the term running instead of progressing, Am I correct?
> 
> I have also added a test for the FlowStepListener similar to that found for the FlowListener
> 
> There exist an issue with me that whenever I call getTaskStats on HadoopStepStats I got an empty hash
> HadoopStepStats stats = (HadoopStepStats)flowStep.getFlowStepStats();
> stats.captureDetail();
> stats.getTaskStats(); //return {}
> 
> also the number of mapper and reducers are always zero
> stats.getNumMapTasks(); //return 0
> 
> one last thing is that the mapProgress and reduceProgress go from zero to 100% directly even if the step is still running and not completed yet
> 
> Is there something wrong I am doing or it may be because I run hadoop using Netbeans
> 
> Thanks in advance and sorry for the long comment!
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by concurrentinc** [comment]
also next time, please apply the patches I provide with my cleanups.

On Nov 19, 2013, at 1:38 PM, Chris K Wensel notifications@github.com wrote:

> those methods aren't wired up since there isn't a way to get the actual values. they should have been deprecated. 
> 
> On Nov 18, 2013, at 1:58 PM, Ahmed Mohsen notifications@github.com wrote: 
> 
> > I have applied the patch manually as it conflicts with my last commit ... I think the major issue is the using of the term running instead of progressing, Am I correct? 
> > 
> > I have also added a test for the FlowStepListener similar to that found for the FlowListener 
> > 
> > There exist an issue with me that whenever I call getTaskStats on HadoopStepStats I got an empty hash 
> > HadoopStepStats stats = (HadoopStepStats)flowStep.getFlowStepStats(); 
> > stats.captureDetail(); 
> > stats.getTaskStats(); //return {} 
> > 
> > also the number of mapper and reducers are always zero 
> > stats.getNumMapTasks(); //return 0 
> > 
> > one last thing is that the mapProgress and reduceProgress go from zero to 100% directly even if the step is still running and not completed yet 
> > 
> > Is there something wrong I am doing or it may be because I run hadoop using Netbeans 
> > 
> > Thanks in advance and sorry for the long comment! 
> > 
> > — 
> > Reply to this email directly or view it on GitHub. 
> 
> ## 
> 
> Chris K Wensel 
> chris@concurrentinc.com 
> http://concurrentinc.com
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by cwensel** [comment]
integrated into wip 2.5. thanks!

**Comment by Ahmed--Mohsen** [comment]
Thanks a lot ... could I know when these patch will be available to be referenced through maven repos

**Comment by concurrentinc** [comment]
might be a while, looks like your test is failing. 

fwiw, the patch you sent wouldn't even compile.

On Nov 19, 2013, at 1:59 PM, Ahmed Mohsen notifications@github.com wrote:

> Thanks a lot ... could I know when these patch will be available to be referenced through maven repos
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by concurrentinc** [comment]
ok, sorry, looks like I was giving a bad patch.. will get a proper one for you to work with.

On Nov 19, 2013, at 2:09 PM, Chris K Wensel notifications@github.com wrote:

> Reopened #26.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by cwensel** [comment]
ok, your test doesn't test anything. please resubmit with it both compiling and testing.

and here is a workable patch I hope, unlike the previous ones. this fixes the compile issue as well.

https://gist.github.com/cwensel/6099bf44526e2c058069

**Comment by Ahmed--Mohsen** [comment]
I am so sorry for the inconvenience ... Everything should be fine now

**Comment by cwensel** [comment]
ok, try number two. 

I pushed the code up, will be a bit before our build system gets to it and cuts a release. closing for now unless something pops up.

thanks!

**Pull request closed without merging**
