### PR TITLE
Kill only jobs that are not complete.

### PR DESCRIPTION
**Pull request by sjlee**
- also added a little more logging for failed jobs

### CODE REVIEW

**Comment by sjlee** [comment]
Comments? Thanks!

**Comment by cwensel** [comment]
will look at it this week before I leave the country. pretty tied up atm.

i'll probably just pull it into 2.5 vs 2.2 so things don't change for 2.2 users too much and we can take the changes further if need be. I also have the other 2.5 changes I need to factor in as well. 

On Oct 21, 2013, at 1:29 PM, Sangjin Lee notifications@github.com wrote:

> Comments? Thanks!
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Chris K Wensel
chris@concurrentinc.com
http://concurrentinc.com

**Comment by sjlee** [comment]
OK thanks.

**Comment by cwensel** [comment]
pushed to wip-2.5. will re-run all our hadoop compat tests to make sure we haven't introduced an api incompatibility.

**Comment by sjlee** [comment]
Thanks!

**Pull request closed without merging**
