### PR TITLE
Abstract out Flow Serialization implementation behind FlowSerialization interface

### PR DESCRIPTION
**Pull request by sritchie**
This pull request abstracts the current FlowStep serialization strategy into `JavaFlowSerializer`, which implements `FlowSerializer`. This will allow the FlowStep serialization mechanism to be pluggable via the `"cascading.flow.serializer"` JobConf property.

### CODE REVIEW

**Comment by johnynek** [comment]
Paired with Sam on this. This really helps scalding and cascalog because users often use objects that are not java.io.Serializable, and Kryo could deal with them, but currently there is no way to plug that in.  This code is almost identical to the old code, but allows us to set a key in the jobConf to change how the serialization is done.

This would be super helpful to have.

**Comment by cwensel** [comment]
go ahead and squash the two commits to get the formatting, and lets not use wildcards for imports if at all possible.

**Comment by cwensel** [comment]
also if you can summarize the commit into CHANGES.txt and use it as the commit message.

**Comment by sritchie** [comment]
Chris, all taken care of. Wildcards removed, CHANGES.txt updated, formatting fixed, commits squashed.

**Comment by cwensel** [comment]
ended up cherry-picking this onto local changes. and did a bit of refactoring. should be out as a wip tomorrow.

**Pull request closed without merging**
