### PR TITLE
Update cascading-core/src/main/java/cascading/tap/BaseTemplateTap.java

### PR DESCRIPTION
**Pull request by derrickburns**
Check for path name aliasing on case insensitive file systems.

### CODE REVIEW

**Comment by cwensel** [comment]
let me think through this, but keeping a map of keys could quickly lead to massive memory issues causing failures when it could be avoided. 

i'd rather just add a switch to force all rendered paths to be lowercase or something.

i've got this issue documented internally so I feel comfortable closing this.

**Comment by derrickburns** [comment]
You are already keeping a map of the _path_ keys.  This map is the same
size.

**Comment by cwensel** [comment]
I do, but I purge it

```
  if( collectors.size() > openTapsThreshold )
    purgeCollectors();
```

i can't purge yours else the issue you are resolving could still trigger.

**Comment by derrickburns** [comment]
Actually, it can't trigger the aliasing problem if by purge you mean
closing all the open collector files.  So, you can purge both.  What this
means is that aliasing can still occur, but will NOT result in file
corruption.

**Comment by derrickburns** [comment]
Two more things.

An option to map to lower case is not necessary, since this can be done at
the user level with no loss of utility of efficiency.

 If you can DETECT that you are writing to a file system that is case
insensitive, then the warning message should be an error message.  This is
actually very simple to do...

**Pull request closed without merging**
