### PR TITLE
enable support for CombineFileInputFormat

### PR DESCRIPTION
**Pull request by sjlee**
This enables support for CombineFileInputFormat in hadoop. CombineFileInputFormat combines a number of small files into a larger split, and improves performance in some situations.

### CODE REVIEW

**Comment by sjlee** [comment]
I'm done with tinkering. :) I would appreciate your review. Thanks.

**Comment by cwensel** [comment]
this stuff is much easier to sort out if it was squashed into a single commit vs wading through the tinkering commits.

regardless I'm still tied up to monday or so before I can give a proper look over.

**Comment by sjlee** [comment]
Thanks. I'll remember to do that next time...

**Comment by cwensel** [comment]
Something about this feature is still making me uncomfortable. But that's my problem to figure out.

As for comments, why not get the individualInputFormatCls name from the child Scheme? seems a bit redundant.

And would there be a benefit to just sub-classing MultiSourceTap? what kind of Tap are you passing in as the parent, GlobHfs? how are multiple taps being combined into a single stream?

**Comment by sjlee** [comment]
Thanks for the comments.

I looked at MultiSourceTap, and extending MultiSourceTap might be a good idea. The current proposal deals with a single instance of Hfs. This is sufficient for the vast majority of the cases (e.g. Hfs for a HDFS directory of many files, etc.). However, by using MultiSourceTap, we could also support the case of many Hfs instances. Let me explore that idea some more. I'll probably create a new pull request for that idea. The Taps we're supporting are Hfs.

**Comment by sjlee** [comment]
Closing this one as the other pull request has been accepted.

**Pull request closed without merging**
