### PR TITLE
Test & Fix for deadlock in Cascading-Local 

### PR DESCRIPTION
**Pull request by cchepelov**
When running scalding's test suite, a test freezes and dies (SkewJoinPipeTest)

This PR provides a simplified test case that exhibits the same blocking behaviour + provides a fix 

The fix works by splitting all edges downstream from a Fork into a separate thread, on the (fair) assumption that downstream consumers are already thread-hardened anyway.
This affects only cascading-local, other backends keep using the same Fork mechanisms as they used to before.

### CODE REVIEW

**Comment by fs111** [comment]
2 things:

1) You are using Java 8 features (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newWorkStealingPool--). We have to stay compatible with Java 7 in Cascading 3.

2) Could you collapse the commits into one?

Thanks!

**Comment by cchepelov** [comment]
Sure ! 

Le 7 janv. 2016 18:36, à 18:36, "André Kelpe" notifications@github.com a écrit:

**Comment by cchepelov** [comment]
done!

**Comment by fs111** [comment]
Thanks! I have done some reformatting and removed some unused imports. It is currenly going through our CI server. I'll update the PR, once it passed.

**Comment by fs111** [comment]
The build is still running, but I already see test failures in Tez:
- JoinFieldedPipesPlatformTest.testForkCoGroupThenHashJoinCoGroupAgain 
- JoinFieldedPipesPlatformTest.testForkThenJoin 

Any idea?

**Comment by cchepelov** [comment]
Le 08/01/2016 15:39, André Kelpe a écrit :

> The build is still running, but I already see test failures in Tez:
> - JoinFieldedPipesPlatformTest.testForkCoGroupThenHashJoinCoGroupAgain
> - JoinFieldedPipesPlatformTest.testForkThenJoin
> 
> Any idea?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cwensel/cascading/pull/47#issuecomment-170019955.

I'd be happy to see the stacks; I added these tests to
cascading-platform (as they should work no matter which fabric). Maybe I
overlooked something? Or perhaps there's something more fundamental at
play here. Is MR1 fine?

Couldn't run the whole test suite here, because of the /other/ deadlock
issue (cf. tweets). Will see (Monday) if I get lucky using targeted runs.

**Comment by cchepelov** [comment]
…no joy here (same "_other_" deadlock issue, job stuck at BaseFlow.complete)
(more on Monday)

**Comment by fs111** [comment]
@cchepelov also with Java 7? 

btw you can run a single test like so:

```
gradle :cascading-hadoop2-tez:platformTest --tests=*.JoinFieldedPipesPlatformTest -i 
```

**Comment by cchepelov** [comment]
Gotta lower the "anti-java7 shields" and reinstall it to verify :) Yes, this deadlocks too in "single test mode" as you describe.

Le 8 janv. 2016 17:31, à 17:31, "André Kelpe" notifications@github.com a écrit:

**Comment by fs111** [comment]
Hadoop is considered vintage computing: Never use an officially supported JVM...

**Comment by cchepelov** [comment]
Or rather: pick whose support you want for your JVM ;)

Le 8 janv. 2016 18:32, à 18:32, "André Kelpe" notifications@github.com a écrit:

**Comment by cchepelov** [comment]
Today's status update:
- some tests were freezing here, because the partition was 90.1% full (no kidding). As this is over 90%, the YARN minicluster failed to fully start (jobs were submitted but that was it, no progress ever, no timeout), starting after test #29, which was the first of the CoGroupFieldedPipesPlatformTest
- java7 or java8 seems neutral here. Yes, this doesn't mean "support", but still.
- I've propagated the hardening against the potential shutdown-immediately-after-submit problem in threadpools (https://github.com/cchepelov/cascading/tree/safe_threadpools), however I now believe I should _not_ necessarily turn that into a pull request (see below)
- now running regtests on all 4 platforms, and will then zoom into the Tez incidents you reported on your CI. So far -local and -hadoop passed, -hadoop2-mr1 (**update**) passed.

With respect to the submit/shutdown: I retract my former suspicion of behaviour change between java8 and java7. On FixedSizeThreadPools, this works fine; compare https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html#shutdown-- and 
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html#shutdown-- (both java8). ForkJoinPool does include this "may or may not execute" clause.

So, as long as this is on java7 and ThreadPoolExecutor, maybe better keep things simple, and not include the startLatches I've started to pepper around (I'll update this PR to reflect this decision, if that's the way you prefer). Or future-proof the thing for the day you drop java7 support and include the start latches (the advantage is that once ForkJoinPool is available, there'll be much less threads to keep spinning around). Let me know.

**Comment by cchepelov** [comment]
Back on

> The build is still running, but I already see test failures in Tez: 
> - JoinFieldedPipesPlatformTest.testForkCoGroupThenHashJoinCoGroupAgain
> - JoinFieldedPipesPlatformTest.testForkThenJoin

JoinFieldedPipesPlatformTest.testForkThenJoin returns zero items on tez, whereas it returns 5 items on -local, -hadoop, -hadoop-mr1. @cwensel , I'm afraid (unless I failed something) I've found a tez vs. rest of the world discrepancy.

JoinFieldedPipesPlatformTest.testForkCoGroupThenHashJoinCoGroupAgain fails clusterside, because of a missed copyFromLocal() of one input file (strange that it now passes). ==> pushing a quick commit for that.

(**update:** now down to JoinFieldedPipesPlatformTest.testForkThenJoin which fails only under tez. Identical behaviour between java7u91 and java8u72)

**Comment by cchepelov** [comment]
Patch updated and smashed back into 1 commit.
One test `@Ignore`'d as it breaks on Tez (really a separate issue I think).

**Comment by fs111** [comment]
JoinFieldedPipesPlatformTest.testForkCoGroupThenHashJoinCoGroupAgain failed again on Tez (linux and java 7). Are you sure, you send me the latest code?

**Comment by cchepelov** [comment]
What? Double checking:
now at 43bb327. Using gradle 2.10 from gradle.com. Using Java7
`LC_ALL=en_US.UTF-8 gradle clean build install` now running

Will advise once it's complete (cc @simondumas)

_Update:_ 

```
BUILD SUCCESSFUL

Total time: 3 hrs 36 mins 7.098 secs
Stopped 0 compiler daemon(s).
```

toolchain manifest:
```java7 cchepelov@TP12:~/workspace/3rd-party/cascading$ gradle -v |grep -v "--"

Gradle 2.10

Build time:   2015-12-21 21:15:04 UTC
Build number: none
Revision:     276bdcded730f53aa8c11b479986aafa58e124a6

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_91 (Oracle Corporation 24.91-b01)
OS:           Linux 4.3.0-1-amd64 amd64```

@fs111 were you able to recover a stack trace or something from the failed test on your side?

**Comment by cchepelov** [comment]
Same on the **Oracle** 7u80 jdk:

``````
ORACLE java7u80 cchepelov@TP12:~/workspace/3rd-party/cascading$ git describe
 3.0-wip-74-159-g43bb327
ORACLE java7u80 cchepelov@TP12:~/workspace/3rd-party/cascading$ gradle -v

------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Build time:   2015-12-21 21:15:04 UTC
Build number: none
Revision:     276bdcded730f53aa8c11b479986aafa58e124a6

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_80 (Oracle Corporation 24.80-b11)
OS:           Linux 4.3.0-1-amd64 amd64```

LC_ALL=en_US.UTF-8 gradle clean :cascading-hadoop2-tez:platformTest --tests=cascading.JoinFieldedPipesPlatformTest.testForkCoGroupThenHashJoinCoGroupAgain --stacktrace --info
``````

(snip)

```
    2016-01-14 10:01:37,611 INFO  flow.Flow (BaseFlow.java:logInfo(1433)) - [cogrouping]  completed in: 00:13.426, using cpu time: 00:10.410
    2016-01-14 10:01:37,640 WARN  server.AuthenticationFilter (AuthenticationFilter.java:doFilter(497)) - AuthenticationToken ignored: org.apache.hadoop.security.authentication.util.SignerException: Invalid signature
    2016-01-14 10:01:37,708 INFO  cascading.PlatformTestCase (PlatformTestCase.java:tearDown(189)) - copying to local /home/cchepelov/workspace/3rd-party/cascading/cascading-hadoop2-tez/build/test/output/hadoop2-tez/joinfieldedpipesplatform/testForkCoGroupThenHashJoinCoGroupAgain/join
Gradle Test Executor 40 finished executing tests.
Finished generating test XML results (0.076 secs) into: /home/cchepelov/workspace/3rd-party/cascading/cascading-hadoop2-tez/build/test-results
Generating HTML test report...
Finished generating test html results (0.07 secs) into: /home/cchepelov/workspace/3rd-party/cascading/cascading-hadoop2-tez/build/reports/tests
:cascading-hadoop2-tez:platformTest (Thread[main,5,main]) completed. Took 56.981 secs.

BUILD SUCCESSFUL

Total time: 1 mins 22.045 secs
```

I guess at this stage, I'm stuck…

**Comment by cwensel** [comment]
I’ve fixed the known underlying issues in wip-3.1.

as for this patch, is there anyway we can not add new test functions and use existing ones like Identity or ExpressionFunction. would be nice to keep this class from growing too large.

with those changes we an re-test and make the commit/push/publish.

**Comment by cchepelov** [comment]
- rebased on wip-3.1
- removed custom functions in `JoinFieldedPipesPlatformTest`, replaced with ExpressionFunctions

**Comment by cwensel** [comment]
I think some cleanup needs to happen here. the patch doesn’t apply, might have to do with the fact its 1.6M and attempts to update every file in my wip-3.1 branch.

update: let me just apply the singular commit..

**Comment by cchepelov** [comment]
Turns out I started this on the wrong branch (wip-3.0). While I could rebase my branch off wip-3.1, I can't rebase the PR itself, I have to open a new one.

**Comment by cchepelov** [comment]
The action continues here: https://github.com/cwensel/cascading/pull/48

**Pull request closed without merging**
