### PR TITLE
Added HashJoinIssueTest, in which single input is used multiple time.

### PR DESCRIPTION
**Pull request by ghost**
As per your suggestion in [Hash join fails giving PlannerException when same input file are used multiple time](https://groups.google.com/forum/#!topic/cascading-user/O215tIepHCo) issue. I have created a test case and raised a pull request.

### CODE REVIEW

**Comment by cwensel** [comment]
ok, there are probably a couple issues here hinged on planning multiple paths for the same file.

I ported this test to the platform test suite so I can test on local mode first, then on the other platforms, and it seems the merge isn't really duplicating the input files.

so I don't think this will be a trivial/fast fix, but you will need to seek workarounds, for example, try using GroupBy as a merge.

I'll leave this open until I sort out all the issues, some of which may simply end up as explicit planner failures, vs the current failure messages.

**Comment by cwensel** [comment]
fwiw, as a workaround, if you put an Identity function after each of the head pipes before the Merge, the planner won't collapse the two paths into a single path. 

definitely the planner should fail here, or retain the multiple paths efficiently (not read the files twice)

**Comment by cwensel** [comment]
OK, still working on this. I’ve decided to take a shot at supporting multi-graph assemblies so very simple dag topologies work as expected. the work will be available in wip 3.2.

but its taking a little more time as its opened up some areas I need to re-address around managing ordinality in forks and joins. 

more soon.

**Comment by cwensel** [comment]
I _think_ i have a working solution. running the regression suite now, if passes tonight, will push a new wip for you to try.

**Comment by cwensel** [comment]
ok, can you try out 3.2-wip-5?

http://conjars.org/cascading/cascading-core/versions/3.2.0-wip-5

**Comment by ghost** [comment]
Hi Chris,

I have tested and it is working.

Thanks
Santlal J Gupta

**Pull request closed without merging**
