### PR TITLE
PlannerException: union of steps have 1 fewer elements than parent assembly

### PR DESCRIPTION
**Pull request by pushpak-gohey**
Added class OptimizationRuleTest in cascading.planner which throws PlannerException for one of the input pipe of CoGroup when executed in
hadoop2-mr1 mode.

### CODE REVIEW

**Comment by cwensel** [comment]
OK, I think I have a fix. Can you checkout and test this branch
https://github.com/cwensel/cascading/tree/wip-3.1-splitjoin

and let me know if the issue is resolved for you?

Thanks!

**Comment by cwensel** [comment]
i moved this to wip-3.0 for a 3.0.2 release, the commit is here

b7c05d59e66028ee3eb740e6c6d6dec6af486334

if you can try cascading 3.0.3-wip-151 that would be helpful. 

will close this if i don’t hear back by next week.

**Comment by pushpak-gohey** [comment]
Hi Chris,

Thank you for looking into this issue. I am not getting error on
3.0.3-wip-151 branch.

However, when I tested it on wip-3.1-splitjoin branch I got different error
related to serialization as below:
java.lang.Exception: cascading.CascadingException: unable to load
serializer for: com.sample.coercetype.ImplicitBigDecimalType from:
org.apache.hadoop.io.serializer.SerializationFactory
at
org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)

I know we have used custom data type (ImplicitBigDecimalType) for which we
are not setting serializer like we are doing for BigDecimal:
TupleSerializationProps.addSerialization(hadoopProps,
BigDecimalSerialization.class.getName());

I think we should add addSerialization for ImplicitBigDecimalType as well
but the question I have is why is it working for 3.0.3-wip-151 branch but
not for wip-3.1-splitjoin. I checked the release note for wip-3.1-splitjoin
and found

_Updated Hadoop, Hadoop2, and Tez serialization and comparator frameworks
to fully leverage declared field type information to reduce serialized data
and perform bitwise equality comparisons. See c.t.h.TupleSerializationProps
to disable bitwise comparisons._

So looks like something about seralization is changed in 3.1. Could you
please explain what has changed, was it using JAVA default serialization
earlier.

Thanks,
Pushpak Gohey

**Comment by cwensel** [comment]
Thanks for the update on the 3.0 wip, i’ll try to back port a couple changes from 3.1 this weekend and push a 3.0.3 next week.

as for the new issue, obviously a test case would help matters. but we did rework and add new reliance on declared types in 3.1 so that we can perform much more efficient serialization during shuffle phases. 

whether this introduces a bug in 3.1, or fixes a bug from 3.0 (and now rightly failing) I don’t know without the test case.

if you can, do make a test against the 3.1 wip branch. 

closing this issue, we can continue the discussion on the new PR.

**Comment by pushpak-gohey** [comment]
Hi Chris,

Thanks for fixing this issue.

And as per your suggestion I have raised another pull request
https://github.com/cwensel/cascading/pull/42 for issue related to
serialization.

Could you please look into it.

Thanks.

**Pull request closed without merging**
