### PR TITLE
Roboustness: catch Unexpected End of File Exception (currupt gzip files)...

### PR DESCRIPTION
**Pull request by rmminusrslash**
for incorrectly closed gzip files, do not crash application if a trap is available. Mark file as  done and continue with next one.

### CODE REVIEW

**Comment by cwensel** [comment]
it would be much easier to identify the changes if the patch hadn't reformatted the original code.

that said, I need to ponder the implications of ignoring corrupted files. 

Traps are intended to capture bad data in the face of business logic failure. corrupted files aren't that.

maybe in 3.x we can introduce a new a way to track bad files (vs bad tuples) and ignore failures in those cases.

**Comment by rmminusrslash** [comment]
Yes, sorry for the reformat. 

Hm, good question. The trap was my inital thought because they deal so nicely with the inevitable breaks which occur at a certain scale. In the log files I work with, most currupt files contain binary rubbish, are currupt due to a logging bug and so on. To me, that was the same class of causes. But I get your argument to seperate the two.

Maybe it makes sense to issue a warning and catch those errors even if no trap is defined.

**Comment by cwensel** [comment]
Agreed, something separate from traps. maybe we can just have a property setting we can set on a Flow (via the FlowConnector or a Tap ConfigDef, so it's not global). 

something like `cascading.input.corrupt.skip = true` (unsure we we have a similar property)

the challenge here is exception handling in that code is a bit fragile (OOME must pass unhindered, and corruption could cause a large malloc). 

if i can see your actual changes, i'll know the likelihood of there being something goofy likely to happen. and we can get this into 2.6 for you to test out.

**Comment by fs111** [comment]
@rmminusrslash I just made this branch public: https://github.com/cwensel/cascading/tree/wip-2.6-tupleentryschemeiterator-exceptions

It gives you the ability to provide us with an array of Exception types, that you want to ignore. Please give it a try and let me know, if this works for you or not.

You will need gradle 1.12. Clone this repo, check out above branch and do `gradle install`. Then you can use cascading-*-2.6.0-wip-dev in your dependant project.

You can use the new feature like so:

```
...
Properties props = new Properties();
TupleEntrySchemeIteratorProps.setPermittedExceptions( props, new Class[]{java.io.EOFException.class} );
FlowConnector flowConnector = HadoopFlowConnector( props );
....
```

If this works for you, we will include it in 2.6.

**Comment by rmminusrslash** [comment]
Hey Andr´e,

not quite working yet. flowProcess.getProperty( TupleEntrySchemeIteratorProps.PERMITTED_EXCEPTIONS ) returns null in TupleEntrySchemeIterator.

Thats my test.

```
@Test
public void testTrapIncorrectlyClosedGzipFile() throws IOException {
    Tap source = new Hfs(new TextDelimited(), "src/test/resources/unexpectedEndOfFile.gz");
    Tap sink = new Hfs(new TextDelimited(), "target/badInputs", SinkMode.REPLACE);
    Tap trap = new Hfs(new TextDelimited(), "target/badInputs_trap");

    Properties props = new Properties();
    TupleEntrySchemeIteratorProps.setPermittedExceptions( props, new Class[]{java.io.EOFException.class} );

    Pipe pipe = new Pipe("data");
    pipe = new Each(pipe, new Identity());

    FlowDef flowDef = FlowDef.flowDef().addSource(pipe, source).addTailSink(pipe, sink).addTrap(pipe, trap);
    Flow flow = new HadoopFlowConnector(props).connect(flowDef);
    flow.complete();
    validateLength(flow.openSink(), 162);

}
```

}

In the current version I could also drop the trap I guess. 

Create a currupt file to test:

$ for i in {1..1000}; do; echo $RANDOM >>numbers; done
$ gzip numbers
$ head -n1 numbers.gz>unexpectedEndOfFile.gz

Lina

**Comment by fs111** [comment]
You are right. The first implementation was to naive. I am working on an update, based on your test. I'll comment here, when that is available.

**Comment by fs111** [comment]
@rmminusrslash I pushed an update to the branch and integrated your test. Please give it another try. It is possible that we are going to change the code, based on the feedback I will get from Chris, but I'd like to know if this is workable for you. 

Thanks!

**Comment by rmminusrslash** [comment]
Hey Andre,

cool,  I will.

Right nie, I'm on holidays without Laptop. I can give it a go next week.

Lina
Am 11.08.2014 16:48 schrieb "André Kelpe" notifications@github.com:

**Comment by rmminusrslash** [comment]
Works fine!

Some minor points:

I might find the syntax confusing as the TupleEntrySchemeIteratorProps adds an entry to the general properties "props" which to me is not apparent from the method name (only if I look at the method itsself). 

Maybe have TupleEntrySchemeIteratorProps.setPermittedExceptions return "props" and call the method "addPermittedExceptions"? Or even have a class "cascadingproperties"? 

Related question:
The user might not know where the EOF exception (for example) occurs, so maybe the need to know that I have to set it in the TupleEntrySchemeIteratorProps is a little too low in the hierarchy?

**Comment by fs111** [comment]
This follows a general pattern in Cascading. There is a Props class whose name matches the class, that reacts to those properties. See for instance:
- http://docs.cascading.org/cascading/2.5/javadoc/cascading/cascade/CascadeProps.html
- http://docs.cascading.org/cascading/2.5/javadoc/cascading/flow/FlowConnectorProps.html
- http://docs.cascading.org/cascading/2.5/javadoc/cascading/tap/hadoop/HfsProps.html

It has to be in the general properties, since all those values simply end up in the configuration of the Flow, which is a JobConf in case of hadop and hadoop2-mr1. We can't use JobConf in the API though, since not all platforms are using a JobConf (like local or Tez in the future).

**Comment by cwensel** [comment]
i pushed this up to the 2.6 wip. should be in conjars in about 3 hours from now. or you can build it yourself.

**Comment by cwensel** [comment]
am closing, please re-open if the implementation in 2.6 isn’t suitable. or bring it up on the mail list.

**Pull request closed without merging**
