### PR TITLE
Added logic to handle combine input for partition taps.

### PR DESCRIPTION
**Pull request by patduin**
Hi,

Here's an attempt to add some logic to handle Combin input flags in combination with a partition tap.
We'll be happy to make any changes and are open for any suggestions

Cheers,
 Patrick

### CODE REVIEW

**Comment by cwensel** [comment]
I’m unsure of the status of this patch, the tests fail.

I’ve put a clean version of the patch here:
- https://github.com/cwensel/cascading/tree/wip-2.7-combined-split-iterator

**Comment by patduin** [comment]
Hi Chris thanks!, I'll have a look at the tests. I'm stuggling a bit with running all the tests sometimes to be honest but I did ran a 
gradle clean cascading-local:test cascading-local:platformTest 
I'll have look and see if I can fix it

**Comment by fs111** [comment]
@patduin cascading-local has nothing to do with hadoop or InputFormats. The best thing to do for those things is to run something like this:

```
gradle clean cascading-hadoop2-mr1:platformTest
```

or if you want a full build do 

```
gradle clean build
```

**Comment by patduin** [comment]
Found the failing test with
gradle clean cascading-hadoop:platformTest

I've missed the hadoop1 edge case I've pushed a fix and improved the test a bit. 
One more commit finetuning the test again. 
That's it from me, happy to hear your feedback

**Comment by cwensel** [comment]
do you mind squashing to a single commit, preferably based on my cleanup branch (squashed in as well)?

it makes dealing with patches much simpler.

**Comment by patduin** [comment]
not a problem, just so I understand correctly. I squash cleanup branch changes + my last changes to one commit then should that be opened in a new pull request to wip-2.7 or keep in this one?

**Comment by cwensel** [comment]
you can put it anywhere you like. pull requests look for branches, not commits (this is why the recommendation is usually to create a feature branch, and overwrite commits there, the PR updates accordingly).

**Comment by patduin** [comment]
Thanks, squashed it into one commit (pulled in your cleanup branch as well). Let me know if I need to do anything else.

**Comment by cwensel** [comment]
looks great so far, running a regression before committing to the public repo for publishing as a wip. should expect it tomorrow sometime.

will close this for now, and re-open if any issues crop up.

**Comment by patduin** [comment]
Thanks a lot for the help!

**Pull request closed without merging**
